version: "3.7"

services:
  traefik:
    labels:
       traefik.enable: true
       traefik.http.routers.api.rule: "Host(`${SUBDOMAIN:-traefik}.${DOMAIN}`) && PathPrefix(`/dashboard`)"
       traefik.http.routers.api.entryPoints: dashboard
       traefik.http.routers.api.rule: "PathPrefix(`/api`) || PathPrefix(`/dashboard`)"
       traefik.http.routers.api.service: api@internal
       # this is necessary for basic auth for the dashboard, check the README first before uncommenting
       #traefik.http.routers.api.middlewares: api-auth
       #traefik.http.middlewares.api-auth.basicauth.users: user/pass
