version: "3.7"

services:
  watchtower:
    image: containrrr/watchtower
    restart: always
    volumes:
      - /etc/timezone:/etc/timezone
      - /var/run/docker.sock:/var/run/docker.sock
      - ./config.json:/config.json
    env_file:
      - watchtower.env
