version: "3.7"

volumes:
  server_data:
    driver: local
    driver_opts:
      type: nfs
      o: addr=${MCSERVERS_NFS_SERVER},${MCSERVERS_NFS_MOUNTOPTS:-rw,nolock}
      device: ${MCSERVERS_NFS_SERVER}:${MCSERVERS_NFS_MOUNT}
  backup_data:
    driver: local
    driver_opts:
      type: nfs
      o: addr=${MCBACKUPS_NFS_SERVER},${MCBACKUPS_NFS_MOUNTOPTS:-rw,nolock}
      device: ${MCBACKUPS_NFS_SERVER}:${MCBACKUPS_NFS_MOUNT}

