version: "3.7"

services:
  minecraft:
    labels:
      traefik.http.routers.crafty.service: crafty
      traefik.http.routers.dynmap.service: dynmap
      traefik.http.routers.dynmap.entrypoints: web-secure
      traefik.http.routers.dynmap.rule: "Host(`${SUBDOMAIN:-dynmap}.${DOMAIN}`)"
      traefik.http.routers.dynmap.tls: true
      traefik.http.routers.dynmap.tls.certresolver: default
      traefik.http.routers.dynmap.middlewares: secHeaders@file
      traefik.http.services.dynmap.loadbalancer.server.port: 8123
      traefik.http.services.dynmap.loadbalancer.healthcheck.port: 8123
